### ISSUE TITLE
Table stripes=none ignored

### ISSUE THREAD

**Issue by hkp-wcd** [asciidoctor/atom-asciidoc-preview#286]
## Description

Table with ```stripes=none``` still has stripes in preview window.
https://asciidoctor.org/docs/user-manual/#striping

- Atom version: 1.34.0 x64
- OS: Windows 10
- `asciidoc-preview` version: 2.12.2
- `language-asciidoc` version: 1.11.0

## Screenshots

![image](https://user-images.githubusercontent.com/42992894/52466696-7aa73780-2b83-11e9-8b07-8a1603e8ccd5.png)

## Syntax example

```adoc
.Table
[stripes=none]
|===
| Something | Column
| Something | Column
|===
```

**Comment by mojavelinux** [comment]
Here's the relevant CSS from the default stylesheet to import:

```css
table.stripes-all tr,table.stripes-odd tr:nth-of-type(odd){background:#f8f8f7}
table.stripes-none tr,table.stripes-odd tr:nth-of-type(even){background:none}
```
